# Keep clippy from getting too creative — strict, no nonsense.
allowed-duplicate-crates = ["serde"]
doc-valid-idents = ["warn"]
enum-variant-size-threshold = 200
type-complexity-threshold = 250
cognitive-complexity-threshold = 25
